# Generated by Django 4.2.5 on 2023-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('sys', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('pr', models.IntegerField()),
            ],
        ),
    ]
